### ISSUE TITLE
Using GitHub secrets 

### ISSUE THREAD

**Issue by samuelmanzanera** [aime-risson/test_aeweb_action#1]
To avoid this:

```
            seed: 'myseed' #Sedd should not be hard coded
```

You can use GitHub secrets. https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by herissondev** [comment]
Hi, yes that was what I planned to do. 
Do you have any recommendations about what the recommended secret name should be? 
Maybe ARCH_SEED ARCHETHIC_SEED , ARCH_BASE_SEED ?
Thanks

**Comment by samuelmanzanera** [comment]
I don't have, as it can only be by project, as the discretion of the person.
Because I don't think you can force an input to be a secret in the Github Actions, right ?

**Comment by herissondev** [comment]
No indeed, not possible. I'll just go with ARCH_BASE_SEED then.

**Comment by herissondev** [comment]
Closed by b418a34
